[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; Libraries we need
lib_deps = 
    adafruit/DHT sensor library@^1.4.6
    ESP8266mDNS                 ; for esp-sensor.local discovery


; Optional: make OTA the default upload method when USB not connected
upload_protocol = espota
upload_port = esp-sensor.local   ; or hardcode your IP if mDNS not working
upload_flags =
    --port=8266
    --auth=mysecretpassword123   ; MUST match code exactly!